# Generated by Django 2.1.5 on 2019-01-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldoption',
            name='formfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.FormField'),
        ),
    ]
