# Generated by Django 2.1.5 on 2019-01-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazz', '0002_auto_20190128_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Sec_edu', models.IntegerField(default=0)),
                ('Sec_vocational_edu', models.IntegerField(default=0)),
                ('Higher_prof_edu_bachelor', models.IntegerField(default=0)),
                ('Wo_master_doctoraal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('house_nr', models.CharField(max_length=10)),
                ('postalcode', models.CharField(max_length=30)),
                ('rent_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_meter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourhoodCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avg_restaurant_dist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Avg_restaurant_amt_1_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Avg_restaurant_amt_3_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Avg_restaurant_amt_5_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Age_0_to_15', models.IntegerField(default=0)),
                ('Age_15_to_25', models.IntegerField(default=0)),
                ('Age_25_to_45', models.IntegerField(default=0)),
                ('Age_45_to_65', models.IntegerField(default=0)),
                ('Age_65_or_older', models.IntegerField(default=0)),
                ('Avg_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Population', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.City')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.Neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StateCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.State')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.StateCity'),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazz.Street'),
        ),
    ]
