# Generated by Django 2.1.5 on 2019-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazz', '0004_neighbourhood_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhoodcity',
            name='Avg_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhoodcity',
            name='Avg_restaurant_amt_1_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhoodcity',
            name='Avg_restaurant_amt_3_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhoodcity',
            name='Avg_restaurant_amt_5_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhoodcity',
            name='Avg_restaurant_dist',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
