# Generated by Django 2.1.5 on 2019-01-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazz', '0006_auto_20190130_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='neighbourhood',
            field=models.ForeignKey(default=16773, on_delete=django.db.models.deletion.CASCADE, to='plazz.Neighbourhood'),
            preserve_default=False,
        ),
    ]
